version: "3"
services:
  db:
    image: "postgres:11.11"
    container_name: "db"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      # Mount init scripts to create the tables and the schemas
      - ./databases/postgres_init/:/docker-entrypoint-initdb.d/
    command:
      - postgres
      - -c
      - 'log_statement=all'
    ports:
      - "5432:5432"

  flyway-one:
    image: bazel/databases/one:one
    command:
      - -url=jdbc:postgresql://db/one
      - -schemas=one
      - -user=user
      - -password=pass
      - -connectRetries=60
      - -locations=filesystem:/flyway/sql,filesystem:/flyway/custom-sql/${CUSTOM_SQL:-dev}-sql/,classpath:db/migration
      - migrate
    environment:
      FLYWAY_PLACEHOLDERS_CUSTOM_COLUMN_NAME: this_column_name_came_from_a_flyway_placeholder
    depends_on:
      - db
