version: "3"
services:
  db:
    image: "postgres:11.11"
    container_name: "db"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    # command: postgres -c max_connections=300
    ports:
      - "5432:5432"
